language: python
python: 
  - "3.5"
install: "pip install -e .[dev,test]"
script: "cd tests && PYTHONPATH=..:$PYTHONPATH python runtests.py"
before_install:
  - wget https://s3.amazonaws.com/mountebank/v1.4/mountebank_1.4.1_amd64.deb
  - sudo dpkg -i mountebank_1.4.1_amd64.deb
